apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ws-calculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: calculator
  name: calculator
  namespace: ws-calculator
spec:
  replicas: 10
  selector:
    matchLabels:
      app: calculator
  strategy: {}
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - image: jeromeguillaume/ws-soap-calculator:latest
        name: ws-soap-calculator
        ports:
        - containerPort: 8080
        env:
        - name: X_SOAP_REGION
          value: soap1
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kong-kong
                  - k6
              topologyKey: topology.kubernetes.io/zone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: calculator2
  name: calculator2
  namespace: ws-calculator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: calculator2
  strategy: {}
  template:
    metadata:
      labels:
        app: calculator2
    spec:
      containers:
      - image: jeromeguillaume/ws-soap-calculator:latest
        name: ws-soap-calculator2
        ports:
        - containerPort: 8080
        env:
        - name: X_SOAP_REGION
          value: soap2
        resources:
          limits:
            cpu: 8
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kong-kong
                  - k6
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calculator
  name: calculator
  namespace: ws-calculator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculator
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calculator2
  name: calculator2
  namespace: ws-calculator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculator2
  type: ClusterIP
