<xsd:schema attributeFormDefault="unqualified" 
            elementFormDefault="qualified" 
            targetNamespace="http://tempuri.org/" 
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            
  <xsd:element name="MultiplyResponse" type="tem:MultiplyResponseType" xmlns:tem="http://tempuri.org/"/>
  <xsd:complexType name="MultiplyResponseType">
    <xsd:sequence>
      <xsd:element type="xsd:integer" name="MultiplyResult"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="DivideResponse" type="tem:DivideResponseType" xmlns:tem="http://tempuri.org/"/>
  <xsd:complexType name="DivideResponseType">
    <xsd:sequence>
      <xsd:element type="xsd:integer" name="DivideResult"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>