FROM kong/kong-gateway:3.12.0.1 AS base

USER root
RUN apt-get update && apt-get install -y build-essential zsh unzip cmake

#########################
# ARM64
#########################
FROM --platform=linux/arm64 base AS build_arm64
COPY ./saxon/zip/SaxonCHE-linux-aarch64-12-8-0.zip /

RUN unzip SaxonCHE-linux-aarch64-12-8-0.zip -d /
RUN rm /SaxonCHE-linux-aarch64-12-8-0.zip

RUN mkdir -p /SaxonCHE-linux-aarch64-12-8-0/kong/build
RUN mkdir -p /SaxonCHE-linux-aarch64-12-8-0/kong/src
WORKDIR /SaxonCHE-linux-aarch64-12-8-0/kong
COPY ./saxon/CMakeLists.txt .
COPY ./saxon/kong-adapter.cpp ./src

WORKDIR /SaxonCHE-linux-aarch64-12-8-0/kong/build
RUN cmake ..
RUN cmake --build .  -- VERBOSE=1
RUN mkdir /usr/local/lib/arm64
RUN cp ./libsaxon-4-kong.so /usr/local/lib/arm64 &&\
    rm -rf SaxonCHE-linux-aarch64-12-8-0
RUN cp /SaxonCHE-linux-aarch64-12-8-0/SaxonCHE/lib/libsaxonc* /usr/local/lib/arm64

#########################
# AMD64
#########################
FROM --platform=linux/amd64 base AS build_amd64
COPY ./saxon/zip/SaxonCHE-linux-x86_64-12-8-0.zip /

RUN unzip SaxonCHE-linux-x86_64-12-8-0.zip -d /
RUN rm /SaxonCHE-linux-x86_64-12-8-0.zip

RUN mkdir -p /SaxonCHE-linux-x86_64-12-8-0/kong/build
RUN mkdir -p /SaxonCHE-linux-x86_64-12-8-0/kong/src
WORKDIR /SaxonCHE-linux-x86_64-12-8-0/kong
COPY ./saxon/CMakeLists.txt .
COPY ./saxon/kong-adapter.cpp ./src

WORKDIR /SaxonCHE-linux-x86_64-12-8-0/kong/build
RUN cmake ..
RUN cmake --build .  -- VERBOSE=1
RUN mkdir /usr/local/lib/amd64
RUN cp ./libsaxon-4-kong.so /usr/local/lib/amd64 &&\
    rm -rf SaxonCHE-linux-x86_64-12-8-0
RUN cp /SaxonCHE-linux-x86_64-12-8-0/SaxonCHE/lib/libsaxonc* /usr/local/lib/amd64

#########################
# Final BUILD
#########################
FROM build_${TARGETARCH} AS build
RUN echo /usr/local/lib > /etc/ld.so.conf.d/local.conf && ldconfig
