FROM kong/kong-gateway:3.8.0.0 as base

USER root
RUN apt-get update && apt-get install -y build-essential zsh unzip

#########################
# ARM64
#########################
FROM --platform=linux/arm64 base as build_arm64
COPY ../zip/libsaxon-HEC-linux-aarch64-v12.5.0.zip /

RUN unzip libsaxon-HEC-linux-aarch64-v12.5.0.zip
RUN rm /libsaxon-HEC-linux-aarch64-v12.5.0.zip
RUN mv /libsaxon-HEC-linux-aarch64-v12.5.0/libs/nix/libsaxon-hec-12.5.0.so /usr/local/lib/

COPY kong-adapter-makefile libsaxon-HEC-linux-aarch64-v12.5.0/Saxon.C.API/Makefile
COPY kong-adapter.cpp libsaxon-HEC-linux-aarch64-v12.5.0/Saxon.C.API/

RUN cd libsaxon-HEC-linux-aarch64-v12.5.0/Saxon.C.API && make 
RUN cp libsaxon-HEC-linux-aarch64-v12.5.0/Saxon.C.API/libsaxon-4-kong.so /usr/local/lib &&\
    rm -rf libsaxon-HEC-linux-aarch64-v12.5.0

#########################
# AMD64
#########################
FROM --platform=linux/amd64 base as build_amd64
COPY ../zip/libsaxon-HEC-linux-x86_64-v12.5.0.zip /

RUN unzip libsaxon-HEC-linux-x86_64-v12.5.0.zip && \
    rm /libsaxon-HEC-linux-x86_64-v12.5.0.zip && \
    mv /libsaxon-HEC-linux-amd64-v12.5.0/libs/nix/libsaxon-hec-12.5.0.so /usr/local/lib/

COPY kong-adapter-makefile libsaxon-HEC-linux-amd64-v12.5.0/Saxon.C.API/Makefile
COPY kong-adapter.cpp libsaxon-HEC-linux-amd64-v12.5.0/Saxon.C.API/

RUN cd libsaxon-HEC-linux-amd64-v12.5.0/Saxon.C.API && make
RUN cp libsaxon-HEC-linux-amd64-v12.5.0/Saxon.C.API/libsaxon-4-kong.so /usr/local/lib && \
    rm -rf /libsaxon-HEC-linux-amd64-v12.5.0

#########################
# Final BUILD
#########################
FROM build_${TARGETARCH} AS build
RUN echo /usr/local/lib > /etc/ld.so.conf.d/local.conf && ldconfig
