apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/version: "3.9"
  name: kong-proxy
  namespace: kong
spec:
  ports:
  - name: kong-proxy-http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: kong-proxy-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: kong
  type: NodePort
