services:
  httpbin:
    hostname: httpbin
    image: svenwal/httpbin:0.9.2
    healthcheck:
      interval: 5s
      retries: 100
      test: ps -ef|grep "/gunicorn -b 0.0.0.0:8080 httpbin:app"|[ `wc -l` -gt 1 ] || exit 1
      timeout: 10s
      disable: ${SERVICE_DISABLE_HEALTHCHECK:-false}
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
    expose:
      - "8080"
