services:
  ws-soap1-calculator:
    hostname: ws.soap1.calculator
    image: jeromeguillaume/ws-soap-calculator:1.0.4
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --fail http://localhost:8080/ws/calculator.wsdl || exit 1
      timeout: 10s
      disable: ${SERVICE_DISABLE_HEALTHCHECK:-false}
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
    expose:
      - "8080"
    environment:
      X_SOAP_REGION: soap1