apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: scen5
spec:
  parallelism: 1
  script:
    configMap:
      name: scen5
      file: scen5.js
  arguments: --tag testId=scen5
  runner:
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 2
        memory: 2Gi
    env:
      - name: K6_SUMMARY_TREND_STATS
        value: 'min,max,avg,p(90),p(95),p(99)'
      - name: K6_PROMETHEUS_RW_TREND_STATS
        value: 'avg,p(90),p(95),p(99),min,max,med,med,count,sum'
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: 'true'
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: 'http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write'
      - name: K6_INSECURE_SKIP_TLS_VERIFY
        value: 'true'
      - name: K6_OUT
        value: experimental-prometheus-rw
      - name: ENTITY_CONFIG_SIZE
        value: '1'
      #- name: K6_VUS
      #  value: '50'
      #- name: k6_DURATION
      #  value: '60s'
      - name: BASIC_AUTH_ENABLED
        value: 'false'
      - name: KEY_AUTH_ENABLED
        value: 'false'
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kong-kong
                - calculator
            topologyKey: kubernetes.io/hostname