apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: calculator-soap-xml-request-handling
  annotations:
    kubernetes.io/ingress.class: kong
plugin: soap-xml-request-handling
config:
  ExternalEntityLoader_Async: false
  ExternalEntityLoader_CacheTTL: 3600
  ExternalEntityLoader_Timeout: 1
  RouteToPath: null
  RouteXPath: null
  RouteXPathCondition: null
  RouteXPathRegisterNs:
  - soap,http://schemas.xmlsoap.org/soap/envelope/
  VerboseRequest: true
  xsdApiSchema: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                      xmlns:tns="http://tempuri.org/"
                      xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                      name="tempuri.org"
                      targetNamespace="http://tempuri.org/">
      <wsdl:documentation>tempuri.org - Add and Subtract calculation
      </wsdl:documentation>
      <wsdl:types>
        <!-- XSD schema for the Request and the Response -->
          <xsd:schema
            xmlns:tns="http://schemas.xmlsoap.org/soap/envelope/"
            targetNamespace="http://schemas.xmlsoap.org/soap/envelope/"
            attributeFormDefault="qualified"
            elementFormDefault="qualified">
          <xsd:import namespace="http://tempuri.org/" schemaLocation="http://localhost:8000/tempuri.org.request-response.xsd"/>
        </xsd:schema>
      </wsdl:types>
    </wsdl:definitions>
  xsdApiSchemaInclude:
    http://localhost:8000/tempuri.org.request-response.xsd: |-
      <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="Add" type="tem:AddType" xmlns:tem="http://tempuri.org/"/>
        <xs:complexType name="AddType">
          <xs:sequence>
            <xs:element type="xs:integer" name="intA" minOccurs="1"/>
            <xs:element type="xs:integer" name="intB" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
        <xs:element name="Subtract" type="tem:SubtractType" xmlns:tem="http://tempuri.org/"/>
        <xs:complexType name="SubtractType">
          <xs:sequence>
            <xs:element type="xs:integer" name="intA" minOccurs="1"/>
            <xs:element type="xs:integer" name="intB" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
        <xs:element name="AddResponse" type="tem:AddResponseType" xmlns:tem="http://tempuri.org/"/>
        <xs:complexType name="AddResponseType">
          <xs:sequence>
            <xs:element type="xs:string" name="AddResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:schema>
  xsdSoapSchema: |-
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://schemas.xmlsoap.org/soap/envelope/"
           targetNamespace="http://schemas.xmlsoap.org/soap/envelope/" >   
      <!-- Envelope, header and body -->
      <xs:element name="Envelope" type="tns:Envelope" />
      <xs:complexType name="Envelope" >
        <xs:sequence>
          <xs:element ref="tns:Header" minOccurs="0" />
          <xs:element ref="tns:Body" minOccurs="1" />
          <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax" />
        </xs:sequence>
        <xs:anyAttribute namespace="##other" processContents="lax" />
      </xs:complexType>
      <xs:element name="Header" type="tns:Header" />
      <xs:complexType name="Header" >
        <xs:sequence>
          <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax" />
        </xs:sequence>
        <xs:anyAttribute namespace="##other" processContents="lax" />
      </xs:complexType>
      <xs:element name="Body" type="tns:Body" />
      <xs:complexType name="Body" >
        <xs:sequence>
          <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax" />
        </xs:sequence>
        <xs:anyAttribute namespace="##any" processContents="lax" >
        <xs:annotation>
          <xs:documentation>
          Prose in the spec does not specify that attributes are allowed on the Body element
        </xs:documentation>
        </xs:annotation>
      </xs:anyAttribute>
      </xs:complexType>
      <!-- Global Attributes.  The following attributes are intended to be usable via qualified attribute names on any complex type referencing them.  -->
      <xs:attribute name="mustUnderstand" >	
        <xs:simpleType>
        <xs:restriction base='xs:boolean'>
        <xs:pattern value='0|1' />
      </xs:restriction>
      </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="actor" type="xs:anyURI" />
      <xs:simpleType name="encodingStyle" >
        <xs:annotation>
        <xs:documentation>
          'encodingStyle' indicates any canonicalization conventions followed in the contents of the containing element.  For example, the value 'http://schemas.xmlsoap.org/soap/encoding/' indicates the pattern described in SOAP specification
        </xs:documentation>
      </xs:annotation>
        <xs:list itemType="xs:anyURI" />
      </xs:simpleType>
      <xs:attribute name="encodingStyle" type="tns:encodingStyle" />
      <xs:attributeGroup name="encodingStyle" >
        <xs:attribute ref="tns:encodingStyle" />
      </xs:attributeGroup>
      <xs:element name="Fault" type="tns:Fault" />
      <xs:complexType name="Fault" final="extension" >
        <xs:annotation>
        <xs:documentation>
          Fault reporting structure
        </xs:documentation>
      </xs:annotation>
        <xs:sequence>
          <xs:element name="faultcode" type="xs:QName" />
          <xs:element name="faultstring" type="xs:string" />
          <xs:element name="faultactor" type="xs:anyURI" minOccurs="0" />
          <xs:element name="detail" type="tns:detail" minOccurs="0" />      
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="detail">
        <xs:sequence>
          <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax" />
        </xs:sequence>
        <xs:anyAttribute namespace="##any" processContents="lax" /> 
      </xs:complexType>
    </xs:schema>
  xsltTransformAfter: null
  xsltTransformBefore: null