apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    server:
      log_level: info
    metrics:
      global:
        scrape_interval: 10s
      configs:
        - name: agent
          scrape_configs:
            - job_name: "k6"
              static_configs:
                - targets: ["k6-service:6565"]
          remote_write:
            - url: "https://prometheus.your-domain.com/api/v1/write"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      containers:
        - name: grafana-agent
          image: grafana/agent:v0.40.1
          args:
            - "--config.file=/etc/agent/agent.yaml"
            - "--enable-features=agent"
          ports:
            - name: http
              containerPort: 12345
          volumeMounts:
            - name: config
              mountPath: /etc/agent
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  selector:
    app: grafana-agent
  ports:
    - name: http
      port: 80
      targetPort: 12345